---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Backend Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: >
          docker-compose run --rm backend sh -c "
            python manage.py test"
        # python manage.py wait_for_db &&
      - name: Lint
        run: docker-compose run --rm backendapp sh -c "flake8"